### ISSUE TITLE
Support sample weights?

### ISSUE THREAD

**Issue by Moelf** [JuliaAI/DecisionTree.jl#141]
https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier.fit

This should make sense right? Not an ML expert but our samples come with drastically different weights.

**Comment by barucden** [comment]
It seems that weights [are supported](https://github.com/bensadeghi/DecisionTree.jl/blob/master/src/classification/tree.jl#L309) to some extent. However, this feature is [not accessible](https://github.com/bensadeghi/DecisionTree.jl/blob/master/src/classification/main.jl#L96) through the API. I think you should be able to make it work just by changing the `build_tree` function as following:
```julia
function build_tree(
        labels              :: AbstractVector{T},
        features            :: AbstractMatrix{S},
        weights :: AbstractVector, # this is new
        n_subfeatures        = 0,
        max_depth            = -1,
        min_samples_leaf     = 1,
        min_samples_split    = 2,
        min_purity_increase  = 0.0;
        loss                 = util.entropy :: Function,
        rng                  = Random.GLOBAL_RNG) where {S, T}

    if max_depth == -1
        max_depth = typemax(Int)
    end
    if n_subfeatures == 0
        n_subfeatures = size(features, 2)
    end

    rng = mk_rng(rng)::Random.AbstractRNG
    t = treeclassifier.fit(
        X                   = features,
        Y                   = labels,
        W                   = weights, # this is changed
        loss                = loss,
        max_features        = Int(n_subfeatures),
        max_depth           = Int(max_depth),
        min_samples_leaf    = Int(min_samples_leaf),
        min_samples_split   = Int(min_samples_split),
        min_purity_increase = Float64(min_purity_increase),
        rng                 = rng)

    return _convert(t.root, t.list, labels[t.labels])
end
```

**Comment by denglerchr** [comment]
I want to use the same functionality, i.e., providing weights to samples. I see the trhead is closed, but we cannot use weights yet. Can this be reopened?

**Comment by rikhuijzer** [comment]
> I want to use the same functionality, i.e., providing weights to samples. I see the trhead is closed, but we cannot use weights yet. Can this be reopened?

This issue is a duplicate of https://github.com/JuliaAI/DecisionTree.jl/issues/72. The main concern appears to be that " it would potentially make the already heavy `Leaf` (and generally, tree) even heavier".
