### ISSUE TITLE
Transfer of ownership?

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/DecisionTree.jl#152]
> Disclaimer: this package is no longer maintained.

@bensadeghi I wonder if you would consider transferring ownership of this package to a Julia organisation for maintenance and, if it suited you, further development. I would support transfer to JuliaAI, for example (I am a member and owner). At the very least, I can see a commitment to minimal maintenance there. Of course, you would also become a member. 

It's also likely that JuliaML would be interested, if you would prefer; I am copying in a member.

 @LoganKilpatrick, DecisionTree.jl is a mature and very popular Julia package worth supporting.

**Comment by logankilpatrick** [comment]
I just sent Ben a message on LinkedIn as well about this

**Comment by bensadeghi** [comment]
@ablaom , thanks for the offer to take over the maintenance of this package.
JuliaAI does look like a good home for it.

@logankilpatrick , would SciML be willing to adopt it?
Any other suitable orgs out there?

**Comment by logankilpatrick** [comment]
I'll defer to @ablaom here, if folks are willing to maintain in the JuliaAI / JuliaML org, that is likely the best home, the SciML folks are already maintaining too many repos (from my perspective).

**Comment by ablaom** [comment]
In think that JuliaML is more focused on deep learning and probably JuliaAI is the most natural home, as reluctant as I am to add to our maintenance burden. Truth is, MLJ (most of JuliaAI) relies heavily on DecisionTrees.jl for testing, documentation, and tutorials. We have a vested interest to keep this package alive.

**Comment by bensadeghi** [comment]
Sounds good @ablaom  
I just tried to transfer ownership of the package to JuliaAI, but I received the following error message:
` You don’t have the permission to create public repositories on JuliaAI `

Should I transfer it to your personal account instead, and have you move it to JuliaAI?

**Comment by ablaom** [comment]
No, no. Now that you have decided I've made you a member. Please accept my invitation and try transfer again.

**Comment by bensadeghi** [comment]
Transferred to JuliaAI

**Comment by ablaom** [comment]
That's great. Let me know if there is anything else I can do.

**Comment by ablaom** [comment]
@bensadeghi  I have now raised your permissions for DecisionTree.jl to the maximum `administrator` level.
