### ISSUE TITLE
Issue to trigger new releases

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/DecisionTree.jl#162]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Add method `wrap` which allows one to wrap a decision tree (`Leaf` or `Node` object) in a new tree structure implementing the AbstractTrees.jl interface. Unlike raw DecisionTree.jl decision trees, the nodes of the wrapped objects can include the names of splitting-features at nodes, and any other node metadata. See the `wrap` docstring for details. (#158) @roland-KA

**Comment by ablaom** [comment]
https://github.com/JuliaRegistries/General/pull/60310

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Add method `wrap` which allows one to wrap a decision tree (`Leaf` or `Node` object) in a new tree structure implementing the AbstractTrees.jl interface. Unlike raw DecisionTree.jl decision trees, the nodes of the wrapped objects can include the names of splitting-features at nodes, and any other node metadata. See the `wrap` docstring for details. (#158) @roland-KA

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**bug fixes**) Ensure `nfoldsCV` passes the RNG on to `AdaBoostClassifier` models. Fix non-threadsafe use of RNGs in random forests (#174) @rikhuijzer 
- (**testing**) Replace all RNGs in tests with `StableRNGs` to ensure consistency across Julia versions and introduce tests over multiple seeds (#174) @rikhuijzer 
- (**enhancement**) Improve display returned by `print_tree`  (making it consistent with the AbstractTrees.jl fallback) and fix docstring (#171, #172, #173) @rikhuijzer

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Bump minimum Julia version to 1.6.
- (**enhancement**) Add methods `impurity_importance`, `split_importance` and `permutation_importance` for all models (#182) @yufongpeng 
- (**breaking**) Use the [SAMME](https://www.intlpress.com/site/pub/pages/journals/items/sii/content/vols/0002/0003/a008/) algorithm for calculating `AdaBoostStumpClassifier` coefficients (#167) @yufongpeng 
- (**breaking**) Do not export the functions `R2`, `mean_sqaure_error`, `majority_vote`, `confusion_matrix` and `ConfusionMatrix` (#183)
- Add `accuracy` to built-in measures but do not export.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Add option to use multithreading in getting predictions for random forests, as in `apply_forest(forest, features; use_multithreading=true)`. The default continues to be no threading. (#188) @salbert83

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) #195 @roland-KA

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**breaking**) For each tree in a random forest models, use `seed!` to put a copy of each associated RNG into a unique state, to mitigate observed correlation between trees (#194, #198) @dhanak @rikhuijzer

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@roland-KA Above includes your recent PR #200 .

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master-0.11.4

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master-0.11.4

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

- (**new feature**) Allow `build_forest(model, features, labels, options...; kwoptions...) -> enlarged_model` to add trees to an existing `model` (#216)

**Comment by rikhuijzer** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**bugfix**) This release fixes a bug where `labels` would internally always be converted to `Float64` (https://github.com/JuliaAI/DecisionTree.jl/pull/226). This is now fixed thanks to @xinadi!
