### ISSUE TITLE
[Feature Request] Add a Field for Feature Importance

### ISSUE THREAD

**Issue by RoyiAvital** [JuliaAI/DecisionTree.jl#170]
It would be great to add to the type a field which describes the _feature importance_ per feature.  
This should match SciKit Learn `RandomForestClassifier`'s / `RandomForestRegressor`'s [`feature_importances_`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier.feature_importances_) output.

**Comment by ablaom** [comment]
Well, there is this open PR:
https://github.com/JuliaAI/DecisionTree.jl/pull/166
