### ISSUE TITLE
Remove the `Int` as rng functionality

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaAI/DecisionTree.jl#177]
Currently, many functions allow users to pass an `Int`or `AbstractRNG` as `rng` argument. In case of an integer, the integer converted to an `AbstractRNG` via

```julia
mk_rng(seed::T) where T <: Integer = Random.MersenneTwister(seed)
```

There are multiple problems with this:

1. This is unstable between Julia versions. So, people who write `rng=1` would reasonably expect that the results are stable between Julia versions. This is not the case which is bad for reproducibility.
2. The code is littered with `mk_rng`  calls. Usually `mk_rng` is called immediately when entering the first public method. **However**, one exception is the threaded loop in `src/classification/main.jl` and `src/regression/main.jl` where the code actually uses the integer to set the seed.
3. It is non-standard Julia. Packages always just take an `AbstractRNG` so that the user can decide what type to use.

@ablaom Should we remove the integer functionality in the breaking change which is coming up with #167? Let me know if yes and I'll make a PR.

**Comment by ablaom** [comment]
> This is unstable between Julia versions. So, people who write rng=1 would reasonably expect that the results are stable between Julia versions. 

Yeah, but as I understand it, doing `rng=MersenneTwister(1)` leads the same issue, which was the reason `StableRNGs` were invented. Basically, Julia has broken RNG behaviour at least twice, as I count it. This was the raison d'etre for introducing `StableRNGs` - stable over all Julia versions (but not sufficiently good for production use). But maybe I have this wrong. 

> The code is littered with mk_rng calls. Usually mk_rng is called immediately when entering the first public method. However, one exception is the threaded loop in src/classification/main.jl and src/regression/main.jl where the code actually uses the integer to set the seed.

Yes, this looks like inconsistent use .

> It is non-standard Julia. Packages always just take an AbstractRNG so that the user can decide what type to use.

True, although MLJ allows RNG's to be integers in lots of places, including some model interfaces.

Overall, I have mixed feelings about this. I agree the principled approach would be to remove this feature - to discourage bad practice and some rare cases of unexpected behaviour. However, it's convenient and, I would miss it when it is gone. 

What do others think?

**Comment by rikhuijzer** [comment]
> True, although MLJ allows RNG's to be integers in lots of places

Then it's probably fine to keep it here too. I didn't know that

> However, it's convenient and, I would miss it when it is gone.

Strong argument
