### ISSUE TITLE
Compatibility bounds for AbstractTrees.jl

### ISSUE THREAD

**Issue by andreuvall** [JuliaAI/DecisionTree.jl#202]
DecisionTree.jl adapted to the new `AbstractNode` type from AbstractTrees.jl in [v0.11.3](https://github.com/JuliaAI/DecisionTree.jl/releases/tag/v0.11.3), but the `Project.toml` file was not updated to reflect the new compatibility bounds with AbstractTrees.jl, which remained at `AbstractTrees = "0.3, 0.4"` ([see diff](https://github.com/JuliaAI/DecisionTree.jl/compare/v0.11.2...v0.11.3#diff-72ed386c2a0cd1d23c0968297e70023ed98c22490d146dd89fc91f48369bad4dL16)). `AbstractNode` was added to AbstractTrees.jl in [v0.4.3](https://github.com/JuliaCollections/AbstractTrees.jl/compare/v0.4.2...v0.4.3). Therefore, the compatibility bounds for DecisionTree.jl on AbstractTrees.jl should have been updated to `AbstractTrees = "0.4.3"` back in v0.11.3.

**Comment by ablaom** [comment]
Todo:

- [ ] Fix in master and release a fix as 0.12.2
- [ ] Release a fix for 0.11 series as 0.11.4
