### ISSUE TITLE
Can offer a interface for DataFrames.jl?

### ISSUE THREAD

**Issue by BNUhex** [JuliaAI/DecisionTree.jl#228]
just do as padas and sklearn do,I think it's a little strange to change data to Matrix before using it.

**Comment by ablaom** [comment]
The [MLJ](https://alan-turing-institute.github.io/MLJ.jl/dev/) Interface for DecisionTree.jl models accepts tabular input, including DataFrames. See for example [here](https://alan-turing-institute.github.io/MLJ.jl/dev/models/RandomForestRegressor_DecisionTree/#RandomForestRegressor_DecisionTree). Is that what you're after?

**Comment by BNUhex** [comment]
> DecisionTree.jl 模型的 [MLJ](https://alan-turing-institute.github.io/MLJ.jl/dev/) 接口接受表格输入，包括 DataFrame。例如，请参阅[此处](https://alan-turing-institute.github.io/MLJ.jl/dev/models/RandomForestRegressor_DecisionTree/#RandomForestRegressor_DecisionTree)。这就是你所追求的吗？

Thank you,it is what I am looking for.
