### ISSUE TITLE
Avoid "regressor" terminology

### ISSUE THREAD

**Issue by andreasnoack** [JuliaAI/DecisionTree.jl#49]
I think the use of "regressor" for a regression tree is unfortunate since a regressor is a *right* hand side variable while what separates the regression tree from a classification tree is the *left* hand side variable. I tried searching for this and it seem like something Scikit-learn came up with. The terminology is e.g. not in Elements of Statistical Learning.

**Comment by cstjean** [comment]
I don't like it much either, but in the context of the ScikitLearn.jl API, it makes sense to copy scikit-learn (they [discussed it too](https://github.com/scikit-learn/scikit-learn/issues/7200)).

I'd be fine changing it.

**Comment by andreasnoack** [comment]
Let's close this one. The SciKitLearn folks believe their terminology "makes sense" even if completely opposite to statistics terminology. What can you do?
